pod 'UMengAnalytics-NO-IDFA'
pod 'AFNetworking', '~> 3.0.1'
pod 'ReactiveCocoa', '~> 2.5'
pod 'MJRefresh', '~> 3.0.7'
pod 'SDWebImage', '~> 3.7.3'
pod 'DACircularProgress', '~> 2.3.1'
pod 'DCKeyValueObjectMapping', '~> 1.5'
pod 'RongCloudIMKit', '~> 2.4.0'
pod 'GetuiSDK', '~> 1.3.1'
pod 'IQKeyboardManager', '~> 3.3.4'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'DZNEmptyDataSet', '~> 1.7.2'
pod 'MWPhotoBrowser', '~> 2.1.1'
pod 'CYLTabBarController', '~> 1.0.5'
platform :ios, ‘7.0’
pod 'LBXScan',:git=>'https://github.com/MxABC/LBXScan.git'