pod 'UMengAnalytics-NO-IDFA'
pod 'AFNetworking'
pod 'ReactiveCocoa'
pod 'MJRefresh'
pod 'SDWebImage'
pod 'DACircularProgress'
pod 'RongCloudIMKit'
pod 'GetuiSDK'
pod 'IQKeyboardManager'
pod 'MBProgressHUD'
pod 'DZNEmptyDataSet'
pod 'MWPhotoBrowser'
pod 'CYLTabBarController'
pod 'MJExtension'
pod 'NSDate-Escort'
pod 'ObjectiveSugar'
pod 'UIViewController+Swizzled'
pod 'UITableView+FDTemplateLayoutCell_Bell'
pod 'dyci', :git => 'https://github.com/DyCI/dyci-main.git'
pod 'SDAutoLayout'
platform :ios, ‘7.0’
pod 'LBXScan',:git=>'https://github.com/MxABC/LBXScan.git'
pod 'SDCycleScrollView'
pod 'SKSTableView'
pod 'Toast'